name: Documentation
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2
        with:
          python-version: 3.x
      - name: Install Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1
      - name: Install dependencies
        run: pip install "sphinx<3" sphinxcontrib-katex toml
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Build
        run: sphinx-build -W -E doc doc/build
      - run: touch doc/build/.nojekyll
