name: Documentation
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: pip install "sphinx<3" sphinxcontrib-katex toml
      - uses: actions/checkout@v2
      - name: Build
        run: sphinx-build -W -E doc doc/build
      - run: touch doc/build/.nojekyll
