---
name: Tests
on: [push, pull_request]
jobs:
  all:
    name: All
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8
          - 3.9
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    runs-on: ubuntu-24.04
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6
      - name: Install MOPAC
        run: |
          sudo apt install mopac
      - name: Install dependencies
        run: uv sync --all-extras --all-groups
      - name: Build
        run: uv build
      - name: Install
        run: uv pip install -f ./dist 'pyberny[test]'
      - name: Test
        run: uv run --extra test coverage run -m pytest -v
