name: Tests
on: [push, pull_request]
jobs:
  all:
    name: All
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8
          - 3.9
          - "3.10"
          - "3.11"
          - "3.12"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Install MOPAC
        run: |
          sudo apt install mopac
        env:
          MOPAC_PASSWORD_URL: ${{ secrets.MOPAC_PASSWORD_URL }}
          MOPAC_DOWNLOAD_URL: ${{ secrets.MOPAC_DOWNLOAD_URL }}
      - name: Create Python virtual environment
        run: |
          python -m venv venv
          echo VIRTUAL_ENV=$PWD/venv >>$GITHUB_ENV
          echo $PWD/venv/bin >>$GITHUB_PATH
          echo venv >>.git/info/exclude
      - name: Install dependencies
        run: pip install -U poetry-dynamic-versioning
      - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: |
            ${{ env.VIRTUAL_ENV }}/bin
            ${{ env.VIRTUAL_ENV }}/lib/python${{ matrix.python-version }}/site-packages
          key: ${{ runner.os }}-${{ matrix.python-version }}
      - name: Build
        run: poetry build
      - name: Install
        run: pip install -U pyberny[test] --pre -f ./dist
      - name: Test
        run: coverage run -m pytest -v
      - name: Upload to Codecov
        run: bash <(curl -s https://codecov.io/bash)
      - name: Uninstall
        run: pip uninstall -y pyberny
